Metrics/BlockLength:
  Exclude:
    - '*.gemspec'
    - 'test/**/*.rb'

Metrics/ClassLength:
  Exclude:
    - 'lib/money/bank/openexchangerates_bank.rb'

Metrics/MethodLength:
  Max: 12

Style/RedundantFreeze:
  Exclude:
    - 'lib/money/bank/openexchangerates_bank.rb'
